version: '3'
services:
 mongodb_server:
    container_name: mongodb_server
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    env_file: './dev.env'
    command:
        - '--auth'
        - '-f'
        - '/etc/mongod.conf'
    volumes:
        - '/home/s/wsf/bitplay-backend/mongo/data/mongod.conf:/etc/mongod.conf'
        - '/home/s/wsf/bitplay-backend/mongo/data/db:/data/db'
        - '/home/s/wsf/bitplay-backend/mongo/data/mongodb:/var/lib/mongodb.'
    ports:
        - '26459:27017'
